wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.29
    code_path: code/team_code_transfuser/train.py
    framework: torch
    is_jupyter_run: false
    python_version: 3.7.13
batch_size:
  desc: null
  value: 25
epochs:
  desc: null
  value: 41
lr:
  desc: null
  value: 0.0001
